name: gh-action-helm-repo
description: Github Action Workflow Playground
inputs:
  repo:
    description: Chart Repo URL
    required: true
  name:
    description: Chart name
    required: true
outputs:
  version: # id of the output
    description: "Latest version"
runs:
  using: "node12"
  main: "./dist/index.js"
