version: "3.7"

services:
  vscode:
    image: "docker.pkg.github.com/nolte/vscode-devcontainers/devops:latest"
    volumes:
      - "../:/go/src/github.com/nolte/gh-action-helm-repo:cached"
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.gnupg:/home/vscode/.gnupg
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.password-store:/home/vscode/.password-store:rw
      ## reuse volumes for extensions
      - gh-action-helm-repo-vol:/home/vscode/.vscode-server/extensions
      # And/or for VS Code Insiders
      - gh-action-helm-repo-vol-insiders:/home/vscode/.vscode-server-insiders/extension
    environment:
      - TZ=Europe/Berlin # $(cat /etc/timezone)
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"
    network_mode: "host"

volumes:
  gh-action-helm-repo-vol:
  gh-action-helm-repo-vol-insiders:
